### ISSUE TITLE
error: ‘std::map<std::__cxx11::basic_string<char>, std::pair<dorydb::AggTreeIndexServer*, dorydb::AggTreeIndexServer*> > QueryServer::AggTrees’ is private within this context   866 |             int depth = server.AggTrees[req->id()].first->depth;

### ISSUE THREAD

**Issue by Feir2** [ucbrise/waldo#8] opened 2023-07-11 02:25 UTC
Hello, when I build waldo, I have encountered the following problem, how can I solve it?

```
user@user-virtual-machine:~/MyFile/waldo-main$ cmake .
-- Option: DEBUG = OFF
-- Finding Protobuf before gRPC
-- Using gRPC 1.48.1
-- Using protobuf 3.19.4
-- Finding Protobuf before gRPC
-- Using gRPC 1.48.1
-- Using protobuf 3.19.4
-- Finding Protobuf before gRPC
-- Using gRPC 1.48.1
-- Using protobuf 3.19.4
-- Finding Protobuf before gRPC
-- Using gRPC 1.48.1
-- Using protobuf 3.19.4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/MyFile/waldo-main

user@user-virtual-machine:~/MyFile/waldo-main$ make
Consolidate compiler generated dependencies of target query_server
[ 92%] Building CXX object server/core/CMakeFiles/query_server.dir/server.cpp.o
/home/user/MyFile/waldo-main/server/core/server.cpp: In member function ‘virtual grpc::Status QueryServiceImpl::SendATQuery(grpc::ServerContext*, const dbquery::QueryATRequest*, dbquery::QueryATResponse*)’:
/home/user/MyFile/waldo-main/server/core/server.cpp:866:32: error: ‘std::map<std::__cxx11::basic_string<char>, std::pair<dorydb::AggTreeIndexServer*, dorydb::AggTreeIndexServer*> > QueryServer::AggTrees’ is private within this context
  866 |             int depth = server.AggTrees[req->id()].first->depth;
      |                                ^~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [server/core/CMakeFiles/query_server.dir/build.make:76：server/core/CMakeFiles/query_server.dir/server.cpp.o] error 1
make[1]: *** [CMakeFiles/Makefile2:1139：server/core/CMakeFiles/query_server.dir/all] error 2
make: *** [Makefile:91：all] error 2
```

**Comment by edauterman** [comment] 2023-07-11 02:34
If you pull, it should be fixed.

**Closed as completed by edauterman** 2023-07-11 02:34 UTC

**Comment by Feir2** [comment] 2023-07-11 02:55
Thank you for your reply, I executed the latest one, but it stopped at 92% and did not continue to execute.

```
user@user-virtual-machine:~/MyFile/waldo-main$ make
...
[ 92%] Built target DCFTableParallelICUnitTest
Consolidate compiler generated dependencies of target DPFTableParallelUnitTest
[ 92%] Built target DPFTableParallelUnitTest
Consolidate compiler generated dependencies of target RollUpUnitTest
[ 92%] Built target RollUpUnitTest
Consolidate compiler generated dependencies of target query_client
[ 92%] Built target query_client
Consolidate compiler generated dependencies of target correctness_tests
[ 92%] Built target correctness_tests
Consolidate compiler generated dependencies of target bench
[ 92%] Built target bench
Consolidate compiler generated dependencies of target query_server
[ 92%] Built target query_server
user@user-virtual-machine:~/MyFile/waldo-main$ 
```

**Comment by Feir2** [comment] 2023-07-11 13:08
Hello! Thank you for your reply. I solved the above problem, but I encountered a new problem when testing locally. Three servers did not print "DONE WITH SETUP" after running ```./build/bin/query_server config/server0.config```. There is also a problem after executing ```./build/bin/bench config/client.config```.  How can I solve it? The details are as follows：

server0-server2:
```
user@user-virtual-machine:~/MyFile/waldo-main$ ./build/bin/query_server config/server0.config
connected to 127.0.0.1:12346
setting up EMP connection as client on address, port 127.0.0.1 32000
connected
setting up EMP connection as server on address, port 0.0.0.0 32002
connected
connected EMP NetIO to 127.0.0.1
```
```
user@user-virtual-machine:~/MyFile/waldo-main$ ./build/bin/query_server config/server1.config
connected to 127.0.0.1:12347
setting up EMP connection as server on address, port 0.0.0.0 32000
connected
setting up EMP connection as client on address, port 127.0.0.1 32001
connected
connected EMP NetIO to 127.0.0.1
```
```
user@user-virtual-machine:~/MyFile/waldo-main$ ./build/bin/query_server config/server2.config
connected to 127.0.0.1:12345
setting up EMP connection as server on address, port 0.0.0.0 32001
connected
setting up EMP connection as client on address, port 127.0.0.1 32002
connected
connected EMP NetIO to 127.0.0.1
```
client:
```
user@user-virtual-machine:~/MyFile/waldo-main$ ./build/bin/bench config/client.config
Num buckets: 2^8 = 256
Window size: 2^8 = 256
finished making query object
batch = 0/0
finished batch 0/0
finished setup
going to generate combined filter
generating filter for cond 0
------------------------------------
[STOPPING TIMER] Total RUNTIME of Gen DCF key: 0 millisec 
------------------------------------
[STOPPING TIMER] Total RUNTIME of Gen DCF key: 0 millisec 
------------------------------------
[STOPPING TIMER] Total RUNTIME of Gen DCF key: 0 millisec 
generating filter for cond 1
------------------------------------
[STOPPING TIMER] Total RUNTIME of Gen DCF key: 0 millisec 
------------------------------------
[STOPPING TIMER] Total RUNTIME of Gen DCF key: 0 millisec 
------------------------------------
...
[STOPPING TIMER] Total RUNTIME of Gen DCF key: 0 millisec 
generating filter for cond 7
------------------------------------
[STOPPING TIMER] Total RUNTIME of Gen DCF key: 0 millisec 
------------------------------------
[STOPPING TIMER] Total RUNTIME of Gen DCF key: 0 millisec 
------------------------------------
[STOPPING TIMER] Total RUNTIME of Gen DCF key: 0 millisec 
generated all base filters
generated combined filter
Query size: 18601B
Query size: 18601B
Query size: 18601B
ERROR receiving message failed to connect to all addresses; last error: UNAVAILABLE: Connection reset by peer
ERROR receiving message failed to connect to all addresses; last error: UNAVAILABLE: Connection reset by peer
ERROR receiving message failed to connect to all addresses; last error: UNAVAILABLE: Connection reset by peer
MAC check passed
```
```
user@user-virtual-machine:~/MyFile/waldo-main$ ./build/bin/correctness_tests
Malicious security with 61 bit statistical security: ON
batch = 0/0
finished batch 0/0
Created DCF table
------------------------------------
[STOPPING TIMER] Total RUNTIME of Gen DCF key: 0 millisec 
------------------------------------
[STOPPING TIMER] Total RUNTIME of Gen DCF key: 0 millisec 
------------------------------------
[STOPPING TIMER] Total RUNTIME of Gen DCF key: 0 millisec 
ERROR receiving message: failed to connect to all addresses; last error: UNAVAILABLE: Connection reset by peer
ERROR receiving message: failed to connect to all addresses; last error: UNAVAILABLE: Connection reset by peer
ERROR receiving message: failed to connect to all addresses; last error: UNAVAILABLE: Connection reset by peer
Returned correct result for DCF table
Created aggregate tree

ERROR receiving message: failed to connect to all addresses; last error: UNAVAILABLE: Connection reset by peer
ERROR receiving message: failed to connect to all addresses; last error: UNAVAILABLE: Connection reset by peer
ERROR receiving message: failed to connect to all addresses; last error: UNAVAILABLE: Connection reset by peer
MAC check passed
batch = 0/0
going to generate combined filter
generating filter for cond 0
------------------------------------
[STOPPING TIMER] Total RUNTIME of gen dpf key: 0 millisec 
------------------------------------
[STOPPING TIMER] Total RUNTIME of gen dpf key: 0 millisec 
------------------------------------
[STOPPING TIMER] Total RUNTIME of gen dpf key: 0 millisec 
generated all base filters
generated combined filter
Query size: 419B
Query size: 419B
Query size: 419B
ERROR receiving message failed to connect to all addresses; last error: UNAVAILABLE: Connection reset by peer
ERROR receiving message failed to connect to all addresses; last error: UNAVAILABLE: Connection reset by peer
ERROR receiving message failed to connect to all addresses; last error: UNAVAILABLE: Connection reset by peer
MAC check passed
Aggregate retrieved: 0
ERROR: returned wrong DPF filter aggregate result 0
 ------ FAILING TESTS ------ 
```
client.config:
```
{
    "addrs": ["127.0.0.1:12345","127.0.0.1:12346","127.0.0.1:12347"],
    "log_window_sz": 8,
    "log_num_buckets": 8,
    "depth": 8,
    "malicious": true,
    "query_type": "range",
    "reps": 1,
    "run_name": "test",
    "num_ands": 8,
    "num_searches": 0,
    "num_appends": 0,
    "seconds": 0,
    "experiment_dir": "/home/ec2-user/dorydb/tmp"
}
```
server0.config:
```
{
    "addrs": ["127.0.0.1:12345","127.0.0.1:12346","127.0.0.1:12347"],
    "server_num": 0,
    "port": "12345",
    "cores": 2,
    "malicious": true 
}
```
server1.config:
```
{
    "addrs": ["127.0.0.1:12345","127.0.0.1:12346","127.0.0.1:12347"],
    "server_num": 1,
    "port": "12346",
    "cores": 2,
    "malicious": true 
}
```
server2.config:
```
{
    "addrs": ["127.0.0.1:12345","127.0.0.1:12346","127.0.0.1:12347"],
    "server_num": 2,
    "port": "12347",
    "malicious": true,
    "cores": 2 
}
```

**Comment by Feir2** [comment] 2023-07-11 13:34
Another problem：
I did not find "config/tree_malicious_throughput.json" in scripts/runExperiment.py line 21, there is just a file called "tree_malicious.json" in scripts/config.

**Comment by edauterman** [comment] 2023-07-12 03:14
For the first issue, the servers should print "DONE WITH SETUP" after roughly 10 seconds. They all need to be started at roughly the same time to have setup performed correctly. I was not able to reproduce the problem that you're seeing (the servers started just fine for me), so it would be worth checking (1) that you're starting the servers one after the other with minimal delay, and (2) that some ports are not blocked. If that doesn't work, then you have some other configuration error.

For the second issue, the `PROPERTY_FILE` value is just a placeholder value. I updated the default value so that it's no longer stale.

**Comment by Feir2** [comment] 2023-07-12 06:51
Sincerely thanks for your help, now it executes successfully.
